spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/imdb?useUnicode=true
        spring:
            datasource:
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB106Dialect