server:
    port: 8080
    shutdown: immediate

spring:
    datasource:
        url: jdbc:h2:mem:imdb;INIT=CREATE SCHEMA IF NOT EXISTS mobilepayment
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
        hikari:
            data-source-properties:
                useConfigs: maxPerformance
                rewriteBatchedStatements: true
                useServerPrepStmts: false
#            maximum-pool-size: 8

    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: always

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none

        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        properties:
            dialect: org.hibernate.dialect.H2Dialect
            hibernate:
                jdbc:
                    batch_size: 1000
                order_inserts: true
                order_updates: true
        generate-ddl: true
        open-in-view: off

    h2:
        console:
            enabled: true
    sql:
        init:
            mode: always

management:
    endpoints:
        web:
            exposure:
                include: '*'
app:
    title-dataset-path: D:/projects/TECHNICAL-ASSIGNMENT/IMDB/dataset/title.basics.tsv
    name-dataset-path: D:/projects/TECHNICAL-ASSIGNMENT/IMDB/dataset/name.basics.tsv
    title-crew-dataset-path: D:/projects/TECHNICAL-ASSIGNMENT/IMDB/dataset/title.crew.tsv
    title-principals-dataset-path: D:/projects/TECHNICAL-ASSIGNMENT/IMDB/dataset/title.principals.tsv
    title-ratings-dataset-path: D:/projects/TECHNICAL-ASSIGNMENT/IMDB/dataset/title.ratings.tsv
#debug: true